name: Delete Linode Resources

on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours (UTC)
  workflow_dispatch:  # Allows manual trigger as well

jobs:
  delete-linode-resources:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo (optional, if you need code access)
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (used for making API requests)
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Run the script to delete resources
      - name: Delete Linode Resources
        env:
          LINODE_API_KEY: ${{ secrets.LINODE_API_KEY }}
        run: |
          python delete_linode_resources.py
